version: '3.9'


services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"



volumes:
    postgres:
