import type {Metadata} from "next";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({

                                     children,
                                   }: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
    <body style={{backgroundColor:"#F1F1F1"}}>{children}</body>
    </html>
  );
}
